### ISSUE TITLE
Replace image used as placeholder

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.lazysizes#1]
We are currently using Plone's spinner as a placeholder and that leads to display it distorted all over the page:

![screen shot 2016-01-21 at 18 15 34](https://cloud.githubusercontent.com/assets/341393/12493208/26dcd1b8-c06b-11e5-94d8-656081cb21e9.png)

We must replace it with a neutral image.

**Comment by rodfersou** [comment]
[This commit](https://github.com/collective/collective.lazysizes/commit/5609e641e55503b8a51b9f22038b2b2238bf5bb1) closes the issue
