### ISSUE TITLE
missing ++resource++collective.lazysizes/ls.respimg.min.js after upgrade

### ISSUE THREAD

**Issue by agitator** [collective/collective.lazysizes#32]
when upgrading from 2.0.5rc1 to 3.0.0 I get this error when I try to recompile the productions bundle by enable/disable dev mode

`  Sorry, the requested resource does not exist.<p>Check the URL and try again.</p><p><b>Resource:</b> http://localhost:11681/Plone/++resource++collective.lazysizes/ls.respimg.min.js</p>
`

is this a leftover? should it be cleaned by an upgrade step - i applied all available steps for the addon

**Comment by hvelarde** [comment]
I suposse you are using Plone 5, right?

**Comment by agitator** [comment]
yes Plone 5, I'll try to look into it the next days

**Comment by hvelarde** [comment]
FYI, @thet is currently fixing the JS mess for Plone 5 in #36.

**Comment by hvelarde** [comment]
@agitator can you confirm if this was fixed?

**Comment by agitator** [comment]
@hvelarde upgraded to 4.0.1 and had no problems so far, but don't have any "older" instance to test

```
2017-12-07 08:48:57 INFO collective.lazysizes JavaScripts resources were cooked
2017-12-07 08:48:57 INFO Products.GenericSetup.tool Profile collective.lazysizes:default upgraded to version ('9',).
```

**Comment by hvelarde** [comment]
ok, closing this one then.
