### ISSUE TITLE
Why only for anonymous?

### ISSUE THREAD

**Issue by gforcada** [collective/collective.lazysizes#34]
We were trying collective.lazysizes at work and only until we looked up at the code we found that the transform was not working because we were logged-in.

Is there any specific reason why the transform is only applied to anonymous users?

It is mentioned at the very end of the README, but it doesn't state the reason.

**Comment by hvelarde** [comment]
the only reason is that was my use case and I wanted to be sure I was not messing around authenticated users, but I can add that feature for you.
