### ISSUE TITLE
4.1.1.1 fails on older browsers with "mismatched anonymous define" error

### ISSUE THREAD

**Issue by thet** [collective/collective.lazysizes#67]
Lazysizes registers itself as an AMD module, if ``define.amd`` is defined.
Doing so results in the infamous failure "Error: Mismatched anonymous define" from RequireJS.

I didn't see this problem with current browsers - maybe the async call of the script is preventing it.
But I get it for Firefox 36 and Safari 9.1 - when not force reloading the site.

``define`` and ``require`` should be undefined/redefined like it's done here:

https://github.com/plone/Products.CMFPlone/blob/3fb2e9c4ce6772ce05623cf3b85e18a76d13dae2/Products/CMFPlone/resources/browser/scripts.pt

**Comment by thet** [comment]
But the fact that it's working with current browsers at the moment is that lazysizes must be loaded at the very end by modern browsers.
Our ReqiuireJS setup in Plone requires resources be properly registered with a name otherwise the "Mismatched" error occurs. The unregistering/reregistering of define/require is normally handled by the resource registry for all non-compiled bundles. Now we have to do it ourselves.
I'm preparing a PR.

**Comment by rodfersou** [comment]
@thet we should not keep looking for those old browsers, the majority of them are "evergreen browsers" what means that they update themselves automatically.

**Comment by rodfersou** [comment]
@thet we find out that using:
```html
<script defer
```
instead of
```html
<script async
```
makes more sense https://community.plone.org/t/help-special-attribute-script-async/7270

maybe this can help with this bug also

**Comment by hvelarde** [comment]
@rodfersou no, every case is different; there's no reason to use `defer` here.

**Comment by rodfersou** [comment]
@hvelarde than you should change from:
```html
<script async...
```
to:
```html
<script async="async"...
```
Since our page template automatically change to:
```html
<script async=""...
```
And this don't work as desired.

**Comment by hvelarde** [comment]
it works as expected; it's in production already.

**Comment by rodfersou** [comment]
Well.. I just see the browser behavior change with async other day.. looked like a mandelbug..

**Comment by hvelarde** [comment]
@thet I have released https://pypi.org/project/collective.lazysizes/4.1.2/ that should fix the issue.

**Comment by rodfersou** [comment]
I found out that our problem was this option that we were missing to generate UMD module without having problems with requirejs https://webpack.js.org/configuration/output/#output-umdnameddefine

Now there are no exception, but in my use case don't work as expected since I have some initialization code that is not running:
https://github.com/collective/collective.cover/blob/use-webpack/webpack/app/cover.js#L13-L34

@thet can you guide me please on how to execute some code after import the library in requirejs?

**Comment by rodfersou** [comment]
maybe the right way is separate in two files.. will dive in more next Monday

**Comment by rodfersou** [comment]
@thet also noticed that even including my library in requirejs the object is not accessible, it should happen because of your comment that Plone reset defaults for some reason.

**Comment by hvelarde** [comment]
let's talk about this in https://community.plone.org/.
