### ISSUE TITLE
Problem with cache

### ISSUE THREAD

**Issue by idgserpro** [collective/collective.lazysizes#69]
I added the ```collective.lazysizes``` in the eggs of a portal that has cache (Varnish).

When I accessed the portal before installing the product, Plone couldn't find the file [++resource ++collective.lazysizes /lazysizes-43c36fc.js](https://github.com/collective/collective.lazysizes/blob/4.1.1.1/webpack/app/resources.pt#L2), because the [resources directory](https://github.com/collective/collective.lazysizes/blob/4.1.1.1/src/collective/lazysizes/browser/configure.zcml#L9) is only available after installation.

This is because the [viewlet](https://github.com/collective/collective.lazysizes/blob/4.1.1.1/src/collective/lazysizes/browser/configure.zcml#L12) that attempts to access the js is available before the product is installed.

At this point, Varnish places the js in cache forever as not found. Since the file isn't in the portal_javascript, even after installing the product, Varnish continues to return the file as not found.

**Comment by erral** [comment]
The solution will be to add the "layer" parameter in the ZCML registration here:

https://github.com/collective/collective.lazysizes/blob/master/src/collective/lazysizes/browser/configure.zcml#L12

**Comment by idgserpro** [comment]
@hvelarde @rodfersou 

Please ensure that this problem doesn't occur in other packages that use webpack.

**Comment by hvelarde** [comment]
@idgserpro we're doing the best we can; I would appreciate code reviews instead of complaints.

**Comment by hvelarde** [comment]
@idgserpro I have released https://pypi.org/project/collective.lazysizes/4.1.2/ that should fix the issue.
