### ISSUE TITLE
In the current master resources.pt is missing

### ISSUE THREAD

**Issue by pbauer** [collective/collective.lazysizes#75]
Startup fails with:

```
zope.configuration.exceptions.ConfigurationError: ('No such file', '/Users/pbauer/workspace/plip/src/collective.lazysizes/src/collective/lazysizes/browser/static/resources.pt')
```

**Comment by hvelarde** [comment]
@pbauer that file is generated by webpack after running buildout:

https://github.com/collective/collective.lazysizes/blob/4.1.4/webpack/app/resources.pt

seems to me you're not using the buildout provided in the package:

https://github.com/collective/collective.lazysizes/blob/4.1.4/buildout.cfg#L49-L52
