### ISSUE TITLE
Load image placeholder using data URI scheme

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.lazysizes#8]
in [src/collective/lazysizes/transform.py](https://github.com/collective/collective.lazysizes/blob/master/src/collective/lazysizes/transform.py#L59-L61) we should use something like this:

```python
IMAGE = """data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA
AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
9TXL0Y4OHwAAAABJRU5ErkJggg=="""
...
        if element.tag == 'img':
            portal_url = api.portal.get().absolute_url()
            element.attrib['src'] = IMAGE
```

this way we save one request per page.

**Comment by ebrehault** [comment]
We could also use the actual image but in low quality by just adding `/mini` at the end of its URL.

**Comment by hvelarde** [comment]
no, by doing that we will duplicate the number of image requests to the backend and increase the page size also; the gray square is fine, I think is a _de facto_ web standard.

**Comment by ebrehault** [comment]
That's true (I proposed it as it would be more beautiful if you have a very long list of images to display in the same page, but I agree it would be less performant).

**Comment by hvelarde** [comment]
there is an additional issue: using `/mini` at the end of the URL will void caching on reverse proxies.

in fact, lazysizes does a pretty good job uploading images in advance; most of the time you don't see the gray square.
