### ISSUE TITLE
Why is 4.1.6 not a 5.0 release?

### ISSUE THREAD

**Issue by agitator** [collective/collective.lazysizes#80]
With theses changes:
- Update lazysizes to v4.1.6. [hvelarde]
- Add support for Plone 5.2 and Python 3. [hvelarde]
- Drop explicit support for Plone 5.0. [hvelarde]
- Code clean up. [hvelarde]

shouldn't it be a 5.x release?

**Comment by hvelarde** [comment]
IMO, Plone 5.0 has many issues and it was difficult to test against it. anyway, this release should work with it, just test it.

**Comment by agitator** [comment]
I share your opinion about Plone 5, question was just about the version increase. Dropping support for a major release would imho be a 5.0 release of c.lazysizes -  https://semver.org ;-)

**Comment by hvelarde** [comment]
you are right, but versioning in this package we follows the one on lazysizes.

as you can see in the changelog I was saying "drop explicit support" that means that it could still work, but we're no longer testing against it.

just upgrade your Plone ;-)

**Comment by agitator** [comment]
ah now I got you ;-)
