### ISSUE TITLE
Release process?

### ISSUE THREAD

**Issue by gforcada** [collective/collective.lazysizes#82]
I want to make a private/temporal release of `collective.lazysizes` while we wait for #81 to be merged and it make its way into an official release.

So, I cloned the repository, created a virtual environment, ran `buildout`, ran `webpack` (as stated on the `README`), but whenever I try to create a release with `zest.releaser` it fails to package the static assets generated by `webpack` :man_shrugging: 

What's the *proper* way to make a release of this package? :thinking:

**Comment by hvelarde** [comment]
I added the instructions in https://github.com/collective/collective.lazysizes/commit/57eec1b6093475486c06f5dd0d52914031347ba7, let me know it that works for you.

**Comment by gforcada** [comment]
@hvelarde thanks :bowing_man: 
There should be some work needed to adapt it, but I once wrote [yarn.build](https://github.com/gforcada/yarn.build) for that specific purpose as well.

**Comment by gforcada** [comment]
I forgot to close it, sorry! 😄
